version: '3.9'

services:
  lama: 
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lama:/lama
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: unless-stopped



  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=lama_dev
      - POSTGRES_USER=lama
      - POSTGRES_PASSWORD=lama