version: '3.9'

services:
  lama: 
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    environment:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - lama

  
volumes:
  postgres_data:
  static_volume:
  media_volume: